### PR TITLE
Add Travis CI to the project

### PR DESCRIPTION
**Pull request by kinow**
Hi,

This pull request adds automated continuous integration through [Travis CI](https://docs.travis-ci.com/user/getting-started/). There is a YAML file, _.travis.yml_ that contains the configuration for Travis CI. And in the README.md, we have a new line that adds the image badge.

It is possible to view what the badge will look like on this branch [https://github.com/kinow/cantaloupe/tree/add-travis](https://github.com/kinow/cantaloupe/tree/add-travis). Look at the README, scrolling down a bit the page.

In order to enable it, you - or another person with administrator rights in GitHub for the repository - would have to go to https://travis-ci.org/, log in with GitHub, look for the medusa-project/cantaloupe-project, and enable it.

There are a few settings in Travis CI that you may be interested in changing, like which branches must be monitored, whether you'd like to have pull requests being tested by it (I personally find it quite useful), etc.

This PR probably depends on https://github.com/medusa-project/cantaloupe/pull/136, to have the `freedeps` Maven profile, which restricts which test are executed.

Travis utilises Ubuntu Trusty, which was *fun* to set up Ffmpeg and OpenJPEG2000. Had to play a few hours till I found the repositories with the right binaries that made the tests pass.

The configuration is also testing with Java 8, and with Java 9. You may want to disable Java 9 if you have no plans to support it in the near future. It may be useful merely as an indicative of how hard it would be to get users with Java 9 in the future to run Cantaloupe.

At the very bottom, I left commented a [Coveralls](https://coveralls.io/) test coverage example. I think right now running the tests will be more useful than actually keeping track of the coverage, but in case you find it useful :-)

I had to try and test a few different configurations, but you can see the latest commit tested here: https://travis-ci.org/kinow/cantaloupe

If you would like to troubleshoot locally, the easiest way I found was to run:

```
$ docker run -it ubuntu:14.04 /bin/bash
$ apt-get update && apt-get upgrade
$ # install wget, git, maven, openjdk-8-jdk, checkout the project and then test it
```

Thanks!
Bruno

### CODE REVIEW

**Comment by kinow** [comment]
Oh, forgot to say, Travis CI also supports Redis by default. You can enable it by some variable I think... so later we can try to enable the Redis tests too. It also comes with Firefox, PhantomJS and a few other tools, so maybe it could even run the ControlPanelTests.

**Comment by kinow** [comment]
:tada:

**Comment by adolski** [comment]
And we have a green icon!

Don't worry, I'll make it red again soon. 😆 

Thanks for all of your work on this, @kinow, All the work you put in made it easy on my end.

I had to disable JDK 9 as we aren't ready for that yet. And, I still need to get this enabled in `release/3.3` which is a little bit behind `develop` in terms of test quality, but I'll work on that as time permits. And will look into the Redis and coverage stuff too. Thanks again.

**Comment by kinow** [comment]
A green icon!!! Did you change anything else? I couldn't get a green icon in my fork. That's great!

>All the work you put in made it easy on my end.

Good for every one. If I get Cantaloupe deployed here, I will be sure to check Travis builds every now and then to follow the development of the features :) and plus if anyone asks how to build the project we can just point at that .travis.yml (I'm getting spoiled by having some many projects with that file).

>I had to disable JDK 9 as we aren't ready for that yet. And, I still need to get this enabled in release/3.3 which is a little bit behind develop in terms of test quality, but I'll work on that as time permits. And will look into the Redis and coverage stuff too. Thanks again.

Interesting. I'm following JDK 9 from a distance for now. Concerned only in keeping up to date with the modules changes that are coming.

In the meantime, I found a few more things to submit via Pull Requests :-) Have some spare time this Friday at work for personal training, so will use that time for writing the code. First PR (#144) submitted. Will submit the other ones in the next hour.

**Pull request merged**
