### PR TITLE
fix standalone war so that it can again launch as documented

### PR DESCRIPTION
**Pull request by hardyoyo**
This pull request will attempt to fix the issue detailed here: https://github.com/medusa-project/cantaloupe/issues/267

### CODE REVIEW

**Comment by adolski** [comment]
Thanks for submitting this, @hardyoyo. I haven't looked at it yet, but I think that adding the logger to the standalone build is not going to work, and it would be better to remove the dependency on the logger from StringUtils.

**Comment by hardyoyo** [comment]
Ah, OK, I'll leave you to it, then. We're in the middle of troubleshooting why we cannot get the standalone war to run after compiling it from the HEAD of the develop branch, and this looked like the best approach. I can drop the logger commit from this, if that's the only objection?

**Comment by adolski** [comment]
Sorry about that. Yes, the logger commit should be removed and any references to the logger from StringUtils would also have to be removed (the two `org.slf4j` imports, the `private static final Logger` assignment, and the usage within `md5()`).

**Comment by hardyoyo** [comment]
I may not be free to work on #267 or #268 any time soon, so I'd not be offended if anyone else wanted to run off with this work from where I've left it.

**Pull request closed without merging**
