### PR TITLE
Docker deploy

### PR DESCRIPTION
**Pull request by kaij**
Added a simple dockerfile to run and test cantaloupe with a docker daemon / docker native. For quickly getting started with local testing.

Build local docker image (tested on OS X with docker native 1.12.5):
`$ sudo docker build -t cantaloupe .`

Run docker image with local images volume:
`$ sudo docker run -d -p 8183:8182 -v ./images:/var/lib/cantaloupe/images --name cantaloupe cantaloupe`

### CODE REVIEW

**Comment by adolski** [comment]
Thanks for submitting this, @kaij. I don't want to bring it into the repo, as I'm not equipped to support or maintain it. But, I would like to link to it from the setup documentation, if you would be willing to host it somewhere. I think it would be appreciated by other Cantaloupe/Docker users. (I know you are not the only one!)

**Comment by kaij** [comment]
Ok, thats fine. For the moment, I'm going to host it at the fork (branch docker-deploy) at https://github.com/kaij/cantaloupe/tree/docker-deploy/docker. In this way, I can also maintain it and handle possible pull requests from other users.

**Comment by adolski** [comment]
Excellent, thanks!

**Comment by pcfens** [comment]
Before working to put together a PR to support Docker, would you be open to it? Since this existing PR is a little over 3 years old I don't want to assume that's still the approach.

Thanks!

**Pull request closed without merging**
